version: '3.8'

services:
  prefixplay:
    build: .
    container_name: prefixplay
    restart: unless-stopped
    ports:
      - "3402:80"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
